[package]
name = "trying-rapier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
rand = "0.8.5"
rapier2d = { version = "0.17.2", features = [ "parallel" ] }
raylib = "3.7.0"
